### ISSUE TITLE
Fails to  compile with the just released 6.2 HWE kernel

### ISSUE THREAD

**Issue by loxK** [Slimbook-Team/slimbook-qc71-dkms#6]
With the [6.2 HWE kernel just released](https://www.omgubuntu.co.uk/2023/08/ubuntu-22-04-linux-kernel-6-2), compilation of this DKMS module fails:

```
/etc/kernel/postinst.d/dkms:
 * dkms: running auto installation service for kernel 6.2.0-26-generic

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j16 KERNELRELEASE=6.2.0-26-generic KDIR=/lib/modules/6.2.0-26-generic/build...^T^M..(bad exit status: 2)
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/slimbook-qc71-dkms.0.crash'
Error! Bad return status for module build on kernel: 6.2.0-26-generic (x86_64)
Consult /var/lib/dkms/slimbook-qc71/0.2.1/build/make.log for more information.
   ...done.
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-6.2.0-26-generic
W: Possible missing firmware /lib/firmware/amdgpu/ip_discovery.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/vega10_cap.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/sienna_cichlid_cap.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/navi12_cap.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/psp_13_0_10_ta.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/psp_13_0_10_sos.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/aldebaran_cap.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/aldebaran_sjt_mec2.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/aldebaran_sjt_mec.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/gc_11_0_3_imu.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/gc_11_0_3_rlc.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/gc_11_0_3_mec.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/gc_11_0_3_me.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/gc_11_0_3_pfp.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/gc_11_0_0_toc.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/sdma_6_0_3.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/sienna_cichlid_mes1.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/sienna_cichlid_mes.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/navi10_mes.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/gc_11_0_3_mes1.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/gc_11_0_3_mes.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/smu_13_0_10.bin for module amdgpu
```

```
» cat /var/lib/dkms/slimbook-qc71/0.2.1/build/make.log
DKMS make.log for slimbook-qc71-0.2.1 for kernel 6.2.0-26-generic (x86_64)
lun. 07 août 2023 09:51:06 +11
make -C /lib/modules/6.2.0-26-generic/build M=/var/lib/dkms/slimbook-qc71/0.2.1/build modules
make[1]: avertissement : jobserver n'est pas disponible : utilisation de -j1. Ajouter « + » à la règle parent du make.
make[1] : on entre dans le répertoire « /usr/src/linux-headers-6.2.0-26-generic »
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-11 (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
  You are using:           gcc-11 (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
  CC [M]  /var/lib/dkms/slimbook-qc71/0.2.1/build/ec.o
  CC [M]  /var/lib/dkms/slimbook-qc71/0.2.1/build/features.o
  CC [M]  /var/lib/dkms/slimbook-qc71/0.2.1/build/main.o
  CC [M]  /var/lib/dkms/slimbook-qc71/0.2.1/build/misc.o
  CC [M]  /var/lib/dkms/slimbook-qc71/0.2.1/build/pdev.o
  CC [M]  /var/lib/dkms/slimbook-qc71/0.2.1/build/events.o
  CC [M]  /var/lib/dkms/slimbook-qc71/0.2.1/build/debugfs.o
  CC [M]  /var/lib/dkms/slimbook-qc71/0.2.1/build/battery.o
/var/lib/dkms/slimbook-qc71/0.2.1/build/battery.c:93:27: error: initialization of ‘int (*)(struct power_supply *, struct acpi_battery_hook *)’ from incompatible pointer type ‘int (*)(struct power_supply *)’ [-Werror=incompatible-pointer-types]
   93 |         .add_battery    = qc71_laptop_batt_add,
      |                           ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/slimbook-qc71/0.2.1/build/battery.c:93:27: note: (near initialization for ‘qc71_laptop_batt_hook.add_battery’)
/var/lib/dkms/slimbook-qc71/0.2.1/build/battery.c:94:27: error: initialization of ‘int (*)(struct power_supply *, struct acpi_battery_hook *)’ from incompatible pointer type ‘int (*)(struct power_supply *)’ [-Werror=incompatible-pointer-types]
   94 |         .remove_battery = qc71_laptop_batt_remove,
      |                           ^~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/slimbook-qc71/0.2.1/build/battery.c:94:27: note: (near initialization for ‘qc71_laptop_batt_hook.remove_battery’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:260 : /var/lib/dkms/slimbook-qc71/0.2.1/build/battery.o] Erreur 1
make[1]: *** [Makefile:2026 : /var/lib/dkms/slimbook-qc71/0.2.1/build] Erreur 2
make[1] : on quitte le répertoire « /usr/src/linux-headers-6.2.0-26-generic »
make: *** [Makefile:25 : all] Erreur 2
```

**Comment by loxK** [comment]
I tried this commit https://github.com/Slimbook-Team/slimbook-qc71-dkms/commit/4b9cac7a672b2054c16eda065556ed444384ee9e (new 0.2.2 is not released in the PPA)

But  it still fails to compile:

```
 * dkms: running auto installation service for kernel 6.2.0-26-generic                                                                                                       
Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j16 KERNELRELEASE=6.2.0-26-generic KDIR=/lib/modules/6.2.0-26-generic/build....(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.2.0-26-generic (x86_64)
Consult /var/lib/dkms/slimbook-qc71/0.2.1/build/make.log for more information.
```


```
# cat /var/lib/dkms/slimbook-qc71/0.2.1/build/make.log
DKMS make.log for slimbook-qc71-0.2.1 for kernel 6.2.0-26-generic (x86_64)
lun. 07 août 2023 10:11:17 +11
make -C /lib/modules/6.2.0-26-generic/build M=/var/lib/dkms/slimbook-qc71/0.2.1/build modules
make[1]: avertissement : jobserver n'est pas disponible : utilisation de -j1. Ajouter « + » à la règle parent du make.
make[1] : on entre dans le répertoire « /usr/src/linux-headers-6.2.0-26-generic »
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-11 (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
  You are using:           gcc-11 (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
  CC [M]  /var/lib/dkms/slimbook-qc71/0.2.1/build/ec.o
  CC [M]  /var/lib/dkms/slimbook-qc71/0.2.1/build/features.o
  CC [M]  /var/lib/dkms/slimbook-qc71/0.2.1/build/main.o
  CC [M]  /var/lib/dkms/slimbook-qc71/0.2.1/build/misc.o
  CC [M]  /var/lib/dkms/slimbook-qc71/0.2.1/build/pdev.o
  CC [M]  /var/lib/dkms/slimbook-qc71/0.2.1/build/events.o
  CC [M]  /var/lib/dkms/slimbook-qc71/0.2.1/build/debugfs.o
  CC [M]  /var/lib/dkms/slimbook-qc71/0.2.1/build/battery.o
/var/lib/dkms/slimbook-qc71/0.2.1/build/battery.c:93:27: error: initialization of ‘int (*)(struct power_supply *, struct acpi_battery_hook *)’ from incompatible pointer type ‘int (*)(struct power_supply *)’ [-Werror=incompatible-pointer-types]
   93 |         .add_battery    = qc71_laptop_batt_add,
      |                           ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/slimbook-qc71/0.2.1/build/battery.c:93:27: note: (near initialization for ‘qc71_laptop_batt_hook.add_battery’)
/var/lib/dkms/slimbook-qc71/0.2.1/build/battery.c:94:27: error: initialization of ‘int (*)(struct power_supply *, struct acpi_battery_hook *)’ from incompatible pointer type ‘int (*)(struct power_supply *)’ [-Werror=incompatible-pointer-types]
   94 |         .remove_battery = qc71_laptop_batt_remove,
      |                           ^~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/slimbook-qc71/0.2.1/build/battery.c:94:27: note: (near initialization for ‘qc71_laptop_batt_hook.remove_battery’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:260 : /var/lib/dkms/slimbook-qc71/0.2.1/build/battery.o] Erreur 1
make[1]: *** [Makefile:2026 : /var/lib/dkms/slimbook-qc71/0.2.1/build] Erreur 2
make[1] : on quitte le répertoire « /usr/src/linux-headers-6.2.0-26-generic »
make: *** [Makefile:25 : all] Erreur 2
```

**Comment by Lt-Henry** [comment]
Hi, I have just checked git version and it compiles with 6.2 HWE.

`sudo make dkmsuninstall && sudo make dkmsinstall` inside slimbook-qc71 dir should do the trick.

**Comment by loxK** [comment]
Can you please release it to the ppa please ?

**Comment by Lt-Henry** [comment]
I guess we will release it at some point of next week. Canonical decided to upgrade kernel 5.x to 6.2 in summer. Not a good idea for a LTS. Anyway, we almost have it.

Btw, did you succeeded with manual installation?

**Comment by Lt-Henry** [comment]
We submitted the fix on ppa. I am going to close this issue but feel free to re-open. I've realized package needs some improvements, at least on debian/ubuntu side, but that would fall on another issue anyway.
